
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable the secrets scanner to allow the Gemini API key to be bundled for the frontend
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  # Python versiyasini belgilash (tavsiya etiladi)
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"

# Telegramdan keladigan so'rovlarni "api/bot" orqali funksiyaga yo'naltirish
[[redirects]]
  from = "/api/bot"
  to = "/.netlify/functions/bot"
  status = 200
